// GENERATED by mod/tools/ida/gen_sigs.py -- do not hand-edit.
// Each pattern is minimal-unique in .text of the build it was
// generated from. rva is a CROSS-CHECK, not the answer.
#pragma once
#include "mgmp_sigscan.h"

namespace mgmp {

// INDEXED BY enum Target -- order is load-bearing.
static const SigTargetDesc kTargetSigs[] = {
    { 0x009A7890, "INIT",
      "40 55 53 56 57 41 54 41 56 41 57 48 8D 6C 24 D9 48 81 EC E0 00 00 00" },
    { 0x008E0010, "NEXTTURN",
      "48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 28 EF FF FF B8 D8 11 00 00 E8 ? ? ? ? 48 2B E0 0F 29 B4 24 C0 11 00 00 48 8B F1" },
    { 0x00137B70, "CHOICE",
      "48 89 5C 24 10 48 89 74 24 18 48 89 7C 24 20 55 41 56 41 57 48 8D AC 24 E0 FB FF FF" },
    { 0x0010DB40, "DOACTION",
      "48 89 5C 24 18 48 89 74 24 20 48 89 54 24 10 55 57 41 54 41 56 41 57 48 8D 6C 24 F0" },
    { 0x00032050, "TRIGGER",
      "48 89 54 24 10 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 68 FD FF FF" },
    { 0x00109FA0, "BEGINTURN",
      "48 89 5C 24 08 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 B0 FC FF FF" },
    { 0x0010B250, "ENDTURN",
      "48 89 5C 24 08 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 A0 FC FF FF" },
    { 0x009A9D80, "FRAME",
      "48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 48 8D 68 A1" },
    { 0x008E1190, "APPLY",
      "48 89 54 24 10 48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 78 F0 FF FF" },
    { 0x008DFC20, "QUEUE",
      "48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 48 89 54 24 10 57 48 83 EC 20 48 8B FA 83 3A 01" },
    { 0x0094B0B0, "RANDINT",
      "48 89 5C 24 08 48 8B 42 08 4C 8B DA 4C 8B 52 18" },
    { 0x00158B80, "RANDFLT",
      "48 89 5C 24 08 48 8B 4A 08 4C 8B DA" },
    { 0x0094B230, "RAND2",
      "40 53 48 83 EC 40 4C 8B 1A 48 8B DA" },
    { 0x0094B550, "ROLL",
      "48 83 EC 38 0F 57 D2 0F 29 74 24 20" },
    { 0x0038E7D0, "MAPUPD",
      "48 8B C4 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 E8 F9 FF FF" },
    { 0x00391050, "ENTERNODE",
      "48 8B C4 48 89 58 08 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 E8 FE FF FF 48 81 EC E0 01 00 00 0F 29 70 B8 0F 29 78 A8 48 8B FA" },
    { 0x001BAD60, "SAVESEL",
      "48 8B C4 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 D8 F1 FF FF" },
    { 0x001BCE90, "SAVESLOT",
      "48 89 5C 24 08 48 89 74 24 10 55 57 41 56 48 8D 6C 24 B9 48 81 EC B0 00 00 00 8B FA" },
    { 0x003A5FC0, "MEWDIR",
      "48 89 5C 24 08 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 D9 48 81 EC E0 00 00 00" },
    { 0x0022C4D0, "SFSTORE",
      "48 89 54 24 10 55 53 56 57 41 56 48 8D 6C 24 C9 48 81 EC F0 00 00 00" },
    { 0x0022C620, "SFLOAD",
      "48 89 5C 24 18 48 89 54 24 10 55 56 57 41 56 41 57 48 8D 6C 24 C9 48 81 EC F0 00 00 00" },
    { 0x00817320, "STATUSMENU",
      "48 8B C4 48 89 58 08 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 B8 FA FF FF" },
    { 0x00937F30, "EVTCHOICE",
      "48 8B 05 ? ? ? ? C6 80 14 07 00 00 01 48 8B 51 08" },
    { 0x009122C0, "EVTUPD",
      "48 8B C4 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 08 FF FF FF" },
    { 0x00382A00, "LVLSELECT",
      "48 89 5C 24 20 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 70 FF FF FF" },
    { 0x00382640, "LVLUPD",
      "48 89 5C 24 08 48 89 74 24 18 55 57 41 54 41 56 41 57 48 8D 6C 24 C9 48 81 EC C0 00 00 00 4C 8B F1" },
    { 0x008DD9C0, "SCUM",
      "48 8B C4 48 89 58 08 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 E8 FE FF FF 48 81 EC E0 01 00 00 0F 29 70 B8 0F 29 78 A8 8B F2" },
    { 0x0024F1C0, "TDELAY",
      "40 55 53 56 57 41 56 48 8D 6C 24 C9 48 81 EC B0 00 00 00 48 8B F9 48 8B 41 18" },
    { 0x002B12F0, "COMBATMENU",
      "48 8B C4 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 18 FC FF FF" },
    { 0x00975F00, "BUTTON",
      "40 55 57 48 8B EC 48 83 EC 48 48 8B F9" },
    { 0x001374D0, "PREVIEWFACE",
      "48 8B C4 48 89 58 10 48 89 70 18 55 57 41 55" },
    { 0x00151CE0, "HILITE",
      "40 53 57 48 81 EC 88 00 00 00 48 8B 01" },
};

// INDEXED BY enum Call -- order is load-bearing.
static const SigTargetDesc kCallSigs[] = {
    { 0x0022E9A0, "SerializeCatData",
      "40 55 53 56 57 41 56 48 8B EC 48 81 EC 80 00 00 00 45 0F B6 F0" },
    { 0x009B3130, "ByteStream::~ByteStream",
      "40 53 48 83 EC 20 80 79 20 00 48 8B D9 74 09" },
    { 0x0032D0A0, "std::ofstream::ofstream",
      "4C 8B DC 49 89 5B 18 49 89 6B 20 89 54 24 10 49 89 4B 08 56 57 41 56 48 83 EC 60 48 8B D9 33 F6 41 89 73 10 48 8D 05 ? ? ? ? 48 89 01 48 89 B1 B0 00 00 00" },
    { 0x000D6980, "CatData::by_id",
      "48 89 5C 24 08 48 89 74 24 20 48 89 54 24 10 57 48 83 EC 40 4C 8B C2" },
    { 0x002E15B0, "Inventory::write_bucket",
      "4C 89 44 24 18 48 89 54 24 10 48 89 4C 24 08 53 55 56 57 41 54 41 55 41 56 41 57 48 83 EC 78 0F 29 74 24 60" },
    { 0x002E1740, "Inventory::read_bucket",
      "48 89 5C 24 10 4C 89 44 24 18 55 56 57 41 56 41 57 48 83 EC 70 4D 8B F1" },
    { 0x000529F0, "glaiel::str_alloc(size_t)",
      "48 83 EC 28 48 85 C9 75 07 33 C0 48 83 C4 28" },
    { 0x00052730, "std::string::_Tidy_deallocate",
      "40 53 48 83 EC 20 48 8B 51 18 48 8B D9 48 83 FA 0F" },
    { 0x0011A840, "Character::get_affecting_elements",
      "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 20 48 8B F2" },
    { 0x0013C570, "Component::im_game_ui",
      "48 89 5C 24 08 57 48 83 EC 20 48 8B 79 18 BA 6A 04 00 00" },
    { 0x0033FFD0, "ImmediateModeGameUI::tile_piece",
      "4C 8B DC 49 89 5B 08 49 89 6B 18 4D 89 4B 20" },
    { 0x00386810, "LevelUpScreen button click",
      "40 53 48 81 EC 10 01 00 00 48 63 41 10" },
    { 0x003B9CE0, "MewDirector::save_adventure",
      "48 8B C4 48 89 58 20 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 68 FE FF FF" },
    { 0x008DD2F0, "RunHistory::serialize",
      "40 53 57 48 83 EC 28 8B 02 48 8B DA" },
    { 0x0013A030, "Brain::DrawAbilityAOE",
      "48 85 D2 0F 84 ? ? ? ? 48 8B C4 4C 89 48 20" },
    { 0x00138A10, "ability highlight (sub_140138A10)",
      "48 85 D2 0F 84 ? ? ? ? 48 8B C4 48 89 50 10 48 89 48 08" },
    { 0x0082E520, "TacticsObject::Move",
      "48 8B C4 48 89 58 10 44 88 40 18 48 89 48 08 55 56 57 41 54 41 55 41 56 41 57 48 8D 68 88" },
    { 0x00101C60, "Character::recompute_stats",
      "48 8B C4 44 88 40 18 48 89 50 10 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 88 FE FF FF" },
    { 0x009764B0, "glaiel::Button::Click",
      "48 89 74 24 18 57 48 83 EC 60 33 F6" },
};

// Globals, recovered from a referencing instruction's own
// RIP-relative displacement rather than by address.
static const SigDataDesc kSigData[] = {
    { 0x013D1970, "MewDirectorPtr",
      "89 54 24 10 4C 8B DC 55 56 57 41 54 41 56 41 57 49 8D 6B A1 48 81 EC B8 00 00 00 48 8B 05 ? ? ? ? 4C 8D 79 10",
      30, 34 },  // via 0x1400689AB in sub_140068990
    { 0x012F2E80, "MouseCache",
      "40 57 48 83 EC 30 83 3D ? ? ? ? 02 48 8B F9 0F 85 ? ? ? ? 80 3D ? ? ? ? 00 74 12 F2 0F 10 15 ? ? ? ? F2 0F 10 1D ? ? ? ? EB 31",
      43, 47 },  // via 0x14097E3F7 in sub_14097E3D0
    { 0x013BB790, "ApplicationBase",
      "48 83 EC 28 B9 38 0F 00 00 E8 ? ? ? ? 48 89 44 24 30 48 8B C8 E8 ? ? ? ? 90 48 89 05 ? ? ? ? 48 83 C4 28",
      31, 35 },  // via 0x14002569C in sub_140025680
};
static const int kSigDataCount = 3;

} // namespace mgmp
